name: stream_reader
version: 1.0.0
description: Asynchronously read from Dart streams.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/stream_reader.git
environment:
  sdk: ">=1.19.0"
dev_dependencies:
  test: ^0.12.15